Incedo_Octavius_Demo_2/Models/BusinessUserSpecialtyModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Incedo_Octavius_Demo_2.Models
{
    public class BusinessUserSpecialtyModel
    {
        [Key]
        public int MapID { get; set; }
        public string SpecialtyMap { get; set; }
        [ScaffoldColumn(false)]
        public int Parent_Specialty_ID { get; set; }
        [ScaffoldColumn(false)]
        public int SpecialtyID { get; set; }
        public string SpecialtyMaster { get; set; }
        
        [ScaffoldColumn(false)]
        List<SelectListItem> SpecialtiesList { get; set; }
    }
}

Incedo_Octavius_Demo_2/Controllers/BusinessUserSpecialtyModelsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Incedo_Octavius_Demo_2.Data;
using Incedo_Octavius_Demo_2.Models;
using MySql.Data.MySqlClient;
using PagedList.Mvc;
using PagedList;

namespace Incedo_Octavius_Demo_2.Controllers
{
    public class BusinessUserSpecialtyModelsController : Controller
    {
        private Incedo_Octavius_Demo_2_BU_Spec_Context db = new Incedo_Octavius_Demo_2_BU_Spec_Context();
        public string constr = ConfigurationManager.ConnectionStrings["Incedo_Octavius_Demo_2_BU_Spec_Context"].ConnectionString;

        // GET: BusinessUserSpecialtyModels
        public ActionResult Index(int ? i)
        {
            List<BusinessUserSpecialtyModel> Spec_BU_List = new List<BusinessUserSpecialtyModel>();
            //string constr = ConfigurationManager.ConnectionStrings["Incedo_Octavius_Demo_2_kol_table_Context"].ConnectionString;
            // Stored Procedures
            using (MySqlConnection dbConnection = new MySqlConnection(constr))
            {
                try
                {
                    dbConnection.Open();
                    MySqlCommand cmd = new MySqlCommand();
                    cmd.Connection = dbConnection;
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.CommandText = "Rules_BU_Spec";

                    MySqlDataAdapter dataAdapter = new MySqlDataAdapter(cmd);
                    DataSet dataSetObject = new DataSet();
                    dataAdapter.Fill(dataSetObject);

                    if (dataSetObject.Tables[0].Rows.Count > 0)
                    {
                        for (int iCout = 0; iCout < dataSetObject.Tables[0].Rows.Count; iCout++)
                        {
                            BusinessUserSpecialtyModel SpecBU = new BusinessUserSpecialtyModel();
                            SpecBU.MapID = Convert.ToInt32(dataSetObject.Tables[0].Rows[iCout]["MapID"]);
                            SpecBU.SpecialtyMap = dataSetObject.Tables[0].Rows[iCout]["SpecialtyMap"].ToString();
                            SpecBU.Parent_Specialty_ID = Convert.ToInt32(dataSetObject.Tables[0].Rows[iCout]["Parent_Speacialty_ID"]);
                            SpecBU.SpecialtyID= Convert.ToInt32(dataSetObject.Tables[0].Rows[iCout]["SpecialityID"]);
                            SpecBU.SpecialtyMaster = dataSetObject.Tables[0].Rows[iCout]["SpecialtyMaster"].ToString();

                            Spec_BU_List.Add(SpecBU);
                        }
                    }

                }
                catch (Exception Ex)
                {

                    Console.WriteLine("Error : " + Ex.Message);
                }

            }
            return View(Spec_BU_List.ToPagedList(i??1,6));
        }

        // GET: BusinessUserSpecialtyModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BusinessUserSpecialtyModel businessUserSpecialtyModel = db.BusinessUserSpecialtyModels.Find(id);
            if (businessUserSpecialtyModel == null)
            {
                return HttpNotFound();
            }
            return View(businessUserSpecialtyModel);
        }

        // GET: BusinessUserSpecialtyModels/Create
        public ActionResult Create()
        {
            List<SpecialtyModel> specialtyList = GetSpecialties();
            ViewBag.SpecialtyListItem = ToSelectList(specialtyList);
            return View();
        }

        // POST: BusinessUserSpecialtyModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MapID,SpecialtyMap,Parent_Specialty_ID,SpecialtyID,SpecialtyMaster")] BusinessUserSpecialtyModel businessUserSpecialtyModel)
        {
            if (ModelState.IsValid)
            {
                using (MySqlConnection dbConnection = new MySqlConnection(constr))
                {
                    try
                    {
                        dbConnection.Open();
                        MySqlCommand cmd = new MySqlCommand();
                        cmd.Connection = dbConnection;
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.CommandText = "Rules_BU_Spec_INSERT";
                        cmd.Parameters.AddWithValue("spec_text", businessUserSpecialtyModel.SpecialtyMap);
                        cmd.Parameters.AddWithValue("spec_id", businessUserSpecialtyModel.Parent_Specialty_ID);
                        cmd.ExecuteNonQuery();
                        dbConnection.Close();

                        /*MySqlDataAdapter dataAdapter = new MySqlDataAdapter(cmd);
                        DataSet dataSetObject = new DataSet();
                        dataAdapter.Fill(dataSetObject);

                        if (dataSetObject.Tables[0].Rows.Count > 0)
                        {
                            for (int iCout = 0; iCout < dataSetObject.Tables[0].Rows.Count; iCout++)
                            {
                                BusinessUserDegreeModel RuleDegBU = new BusinessUserDegreeModel();
                                RuleDegBU.MapID = Convert.ToInt32(dataSetObject.Tables[0].Rows[iCout]["MapID"]);
                                RuleDegBU.DegreeID = Convert.ToInt32(dataSetObject.Tables[0].Rows[iCout]["DegreeID"]);
                                RuleDegBU.Degree_Map = dataSetObject.Tables[0].Rows[iCout]["Degree_Map"].ToString();
                                RuleDegBU.Parent_Degree_ID = Convert.ToInt32(dataSetObject.Tables[0].Rows[iCout]["Parent_Degree_ID"]);
                                RuleDegBU.Degree_Master = dataSetObject.Tables[0].Rows[iCout]["Degree_Master"].ToString();

                                RuleDegBU_List.Add(RuleDegBU);
                            }
                        }*/

                    }
                    catch (Exception Ex)
                    {

                        Console.WriteLine("Error : " + Ex.Message);
                    }

                }

                return RedirectToAction("Index");
            }

            return View(businessUserSpecialtyModel);
        }

        // GET: BusinessUserSpecialtyModels/Edit/5
        public ActionResult Edit(int? id)
        {
            List<BusinessUserSpecialtyModel> SpecBU_List = new List<BusinessUserSpecialtyModel>();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<SpecialtyModel> specialtyList = GetSpecialties();
            ViewBag.SpecialtyListItem = ToSelectList(specialtyList);

            using (MySqlConnection dbConnection = new MySqlConnection(constr))
            {
                try
                {
                    dbConnection.Open();
                    MySqlCommand cmd = new MySqlCommand();
                    cmd.Connection = dbConnection;
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.CommandText = "Rules_BU_Spec_pm";
                    cmd.Parameters.AddWithValue("id", id);

                    MySqlDataAdapter dataAdapter = new MySqlDataAdapter(cmd);
                    DataSet dataSetObject = new DataSet();
                    dataAdapter.Fill(dataSetObject);

                    if (dataSetObject.Tables[0].Rows.Count > 0)
                    {
                        for (int iCout = 0; iCout < dataSetObject.Tables[0].Rows.Count; iCout++)
                        {
                            BusinessUserSpecialtyModel SpecBU = new BusinessUserSpecialtyModel();
                            SpecBU.MapID = Convert.ToInt32(dataSetObject.Tables[0].Rows[iCout]["MapID"]);
                            SpecBU.SpecialtyMap = dataSetObject.Tables[0].Rows[iCout]["SpecialtyMap"].ToString();
                            SpecBU.Parent_Specialty_ID = Convert.ToInt32(dataSetObject.Tables[0].Rows[iCout]["Parent_Speacialty_ID"]);
                            SpecBU.SpecialtyID = Convert.ToInt32(dataSetObject.Tables[0].Rows[iCout]["SpecialityID"]);
                            SpecBU.SpecialtyMaster = dataSetObject.Tables[0].Rows[iCout]["SpecialtyMaster"].ToString();

                            SpecBU_List.Add(SpecBU);
                        }
                    }

                }
                catch (Exception Ex)
                {

                    Console.WriteLine("Error : " + Ex.Message);
                }

            }


            return View(SpecBU_List[0]);
        }

        // POST: BusinessUserSpecialtyModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MapID,SpecialtyMap,Parent_Specialty_ID,SpecialtyID,SpecialtyMaster")] BusinessUserSpecialtyModel businessUserSpecialtyModel)
        {
            if (ModelState.IsValid)
            {
                ViewBag.map_id = businessUserSpecialtyModel.MapID;
                ViewBag.deg_text = businessUserSpecialtyModel.SpecialtyMap;
                ViewBag.deg_id = businessUserSpecialtyModel.Parent_Specialty_ID;
                /*if (businessUserDegreeModel == null)
                {
                    return HttpNotFound();
                }*/
                using (MySqlConnection dbConnection = new MySqlConnection(constr))
                {
                    try
                    {

Incedo_Octavius_Demo_2/Views/BusinessUserSpecialtyModels/Create.cshtml
@model Incedo_Octavius_Demo_2.Models.BusinessUserSpecialtyModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BusinessUserSpecialtyModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SpecialtyMap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SpecialtyMap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SpecialtyMap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SpecialtyMaster, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.SpecialtyMaster, new { htmlAttributes = new { @class = "form-control" } })*@

                @Html.DropDownListFor(model => model.Parent_Specialty_ID, ViewBag.SpecialtyListItem as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SpecialtyMaster, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Incedo_Octavius_Demo_2/Views/BusinessUserSpecialtyModels/Delete.cshtml
@model Incedo_Octavius_Demo_2.Models.BusinessUserSpecialtyModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BusinessUserSpecialtyModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SpecialtyMap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialtyMap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpecialtyMaster)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialtyMaster)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Incedo_Octavius_Demo_2/Views/BusinessUserSpecialtyModels/Details.cshtml
@model Incedo_Octavius_Demo_2.Models.BusinessUserSpecialtyModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BusinessUserSpecialtyModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SpecialtyMap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialtyMap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpecialtyMaster)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialtyMaster)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MapID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Incedo_Octavius_Demo_2/Views/BusinessUserSpecialtyModels/Edit.cshtml
@model Incedo_Octavius_Demo_2.Models.BusinessUserSpecialtyModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BusinessUserSpecialtyModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MapID)

        <div class="form-group">
            @Html.LabelFor(model => model.SpecialtyMap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SpecialtyMap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SpecialtyMap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SpecialtyMaster, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.SpecialtyMaster, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Degree_Master, "", new { @class = "text-danger" })*@

                @Html.DropDownListFor(model => model.Parent_Specialty_ID, ViewBag.SpecialtyListItem as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SpecialtyMaster, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Incedo_Octavius_Demo_2/Views/BusinessUserSpecialtyModels/Index.cshtml
@model IPagedList<Incedo_Octavius_Demo_2.Models.BusinessUserSpecialtyModel>

@{
    ViewBag.Title = "Index";
}
@using PagedList.Mvc;
@using PagedList;

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().SpecialtyMap)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().SpecialtyMaster)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SpecialtyMap)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SpecialtyMaster)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.MapID }) |
            @*@Html.ActionLink("Details", "Details", new { id=item.MapID }) |*@
            @Html.ActionLink("Delete", "Delete", new { id = item.MapID })
        </td>
    </tr>
}

</table>
@Html.PagedListPager(Model, i => Url.Action("Index", "BusinessUserSpecialtyModels", new {i,search=Request.QueryString["search"]}))