Incedo_Octavius_Demo_2/Models/BusinessUserDegreeModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Incedo_Octavius_Demo_2.Models
{
    public class BusinessUserDegreeModel
    {
        [Key]
        public int? MapID { get; set; }
        public string Degree_Map { get; set; }

        [ScaffoldColumn(false)]
        public int? Parent_Degree_ID { get; set; }
        
        [ScaffoldColumn(false)]
        public int? DegreeID { get; set; }
        
        public string Degree_Master { get; set; }

        [ScaffoldColumn(false)]
        public List<SelectListItem> DegreesList { get; set; }

    }
}

Incedo_Octavius_Demo_2/Controllers/BusinessUserDegreeModelsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Incedo_Octavius_Demo_2.Data;
using Incedo_Octavius_Demo_2.Models;
using MySql.Data.MySqlClient;
using PagedList.Mvc;
using PagedList;

namespace Incedo_Octavius_Demo_2.Controllers
{
    
    public class BusinessUserDegreeModelsController : Controller
    {

        private Incedo_Octavius_Demo_2_Rules_BU_Deg_Context db = new Incedo_Octavius_Demo_2_Rules_BU_Deg_Context();
        public string constr = ConfigurationManager.ConnectionStrings["Incedo_Octavius_Demo_2_Rules_BU_Deg_Context"].ConnectionString;

        // GET: BusinessUserDegreeModels
        public ActionResult Index(int ? i)
        {
            List<BusinessUserDegreeModel> RuleDegBU_List = new List<BusinessUserDegreeModel>();
            //string constr = ConfigurationManager.ConnectionStrings["Incedo_Octavius_Demo_2_kol_table_Context"].ConnectionString;
            // Stored Procedures
            using (MySqlConnection dbConnection = new MySqlConnection(constr))
            {
                try
                {
                    dbConnection.Open();
                    MySqlCommand cmd = new MySqlCommand();
                    cmd.Connection = dbConnection;
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.CommandText = "Rules_BU_Deg";

                    MySqlDataAdapter dataAdapter = new MySqlDataAdapter(cmd);
                    DataSet dataSetObject = new DataSet();
                    dataAdapter.Fill(dataSetObject);

                    if (dataSetObject.Tables[0].Rows.Count > 0)
                    {
                        for (int iCout = 0; iCout < dataSetObject.Tables[0].Rows.Count; iCout++)
                        {
                            BusinessUserDegreeModel RuleDegBU = new BusinessUserDegreeModel();
                            RuleDegBU.MapID = Convert.ToInt32(dataSetObject.Tables[0].Rows[iCout]["MapID"]);
                            RuleDegBU.DegreeID = Convert.ToInt32(dataSetObject.Tables[0].Rows[iCout]["DegreeID"]);
                            RuleDegBU.Degree_Map = dataSetObject.Tables[0].Rows[iCout]["Degree_Map"].ToString();
                            RuleDegBU.Parent_Degree_ID = Convert.ToInt32(dataSetObject.Tables[0].Rows[iCout]["Parent_Degree_ID"]);
                            RuleDegBU.Degree_Master = dataSetObject.Tables[0].Rows[iCout]["Degree_Master"].ToString();

                            RuleDegBU_List.Add(RuleDegBU);
                        }
                    }
                    
                }
                catch (Exception Ex)
                {

                    Console.WriteLine("Error : " + Ex.Message);
                }

            }
            return View(RuleDegBU_List.ToPagedList(i ??  1,6));
            //return View(db.BusinessUserDegreeModels.ToList());
        }

        // GET: BusinessUserDegreeModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BusinessUserDegreeModel businessUserDegreeModel = db.BusinessUserDegreeModels.Find(id);
            if (businessUserDegreeModel == null)
            {
                return HttpNotFound();
            }
            return View(businessUserDegreeModel);
        }

        // GET: BusinessUserDegreeModels/Create
        public ActionResult Create()
        {
            //BusinessUserDegreeModel model = new BusinessUserDegreeModel();
            //model.DegreesList = PopulateDegrees();

            List<DegreeModel> degreeList = GetDegrees();
            ViewBag.DegreeListItem = ToSelectList(degreeList);

            return View();
        }

        // POST: BusinessUserDegreeModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MapID,Degree_Map,Parent_Degree_ID,DegreeID,Degree_Master")] BusinessUserDegreeModel businessUserDegreeModel)
        {

            if (ModelState.IsValid)
            {
                using (MySqlConnection dbConnection = new MySqlConnection(constr))
                {
                    try
                    {
                        dbConnection.Open();
                        MySqlCommand cmd = new MySqlCommand();
                        cmd.Connection = dbConnection;
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.CommandText = "Rules_BU_Deg_INSERT";
                        cmd.Parameters.AddWithValue("deg_text", businessUserDegreeModel.Degree_Map);
                        cmd.Parameters.AddWithValue("deg_id", businessUserDegreeModel.Parent_Degree_ID);
                        cmd.ExecuteNonQuery();
                        dbConnection.Close();

                        /*MySqlDataAdapter dataAdapter = new MySqlDataAdapter(cmd);
                        DataSet dataSetObject = new DataSet();
                        dataAdapter.Fill(dataSetObject);

                        if (dataSetObject.Tables[0].Rows.Count > 0)
                        {
                            for (int iCout = 0; iCout < dataSetObject.Tables[0].Rows.Count; iCout++)
                            {
                                BusinessUserDegreeModel RuleDegBU = new BusinessUserDegreeModel();
                                RuleDegBU.MapID = Convert.ToInt32(dataSetObject.Tables[0].Rows[iCout]["MapID"]);
                                RuleDegBU.DegreeID = Convert.ToInt32(dataSetObject.Tables[0].Rows[iCout]["DegreeID"]);
                                RuleDegBU.Degree_Map = dataSetObject.Tables[0].Rows[iCout]["Degree_Map"].ToString();
                                RuleDegBU.Parent_Degree_ID = Convert.ToInt32(dataSetObject.Tables[0].Rows[iCout]["Parent_Degree_ID"]);
                                RuleDegBU.Degree_Master = dataSetObject.Tables[0].Rows[iCout]["Degree_Master"].ToString();

                                RuleDegBU_List.Add(RuleDegBU);
                            }
                        }*/

                    }
                    catch (Exception Ex)
                    {

                        Console.WriteLine("Error : " + Ex.Message);
                    }

                }

                return RedirectToAction("Index");
            }

            return View(businessUserDegreeModel);
        }

        // GET: BusinessUserDegreeModels/Edit/5
        public ActionResult Edit(int? id)
        {
            List<BusinessUserDegreeModel> RuleDegBU_List = new List<BusinessUserDegreeModel>();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.msg = id;
            //BusinessUserDegreeModel businessUserDegreeModel = db.BusinessUserDegreeModels.Find(id);
            //BusinessUserDegreeModel model = new BusinessUserDegreeModel();
            //model.DegreesList = PopulateDegrees();
            List<DegreeModel> degreeList = GetDegrees();
            ViewBag.DegreeListItem = ToSelectList(degreeList);

            using (MySqlConnection dbConnection = new MySqlConnection(constr))
            {
                try
                {
                    dbConnection.Open();
                    MySqlCommand cmd = new MySqlCommand();
                    cmd.Connection = dbConnection;
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.CommandText = "Rules_BU_Deg_pm";
                    cmd.Parameters.AddWithValue("id", id);

                    MySqlDataAdapter dataAdapter = new MySqlDataAdapter(cmd);
                    DataSet dataSetObject = new DataSet();
                    dataAdapter.Fill(dataSetObject);

                    if (dataSetObject.Tables[0].Rows.Count > 0)
                    {
                        for (int iCout = 0; iCout < dataSetObject.Tables[0].Rows.Count; iCout++)
                        {
                            BusinessUserDegreeModel RuleDegBU = new BusinessUserDegreeModel();
                            RuleDegBU.MapID = Convert.ToInt32(dataSetObject.Tables[0].Rows[iCout]["MapID"]);
                            RuleDegBU.DegreeID = Convert.ToInt32(dataSetObject.Tables[0].Rows[iCout]["DegreeID"]);
                            RuleDegBU.Degree_Map = dataSetObject.Tables[0].Rows[iCout]["Degree_Map"].ToString();
                            RuleDegBU.Parent_Degree_ID = Convert.ToInt32(dataSetObject.Tables[0].Rows[iCout]["Parent_Degree_ID"]);
                            RuleDegBU.Degree_Master = dataSetObject.Tables[0].Rows[iCout]["Degree_Master"].ToString();

                            RuleDegBU_List.Add(RuleDegBU);
                        }
                    }

                }
                catch (Exception Ex)
                {

                    Console.WriteLine("Error : " + Ex.Message);
                }

            }


            return View(RuleDegBU_List[0]);
            //return View();
        }

        // POST: BusinessUserDegreeModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MapID,Degree_Map,Parent_Degree_ID,DegreeID,Degree_Master")] BusinessUserDegreeModel businessUserDegreeModel)
        {
            if (ModelState.IsValid)
            {
                ViewBag.map_id = businessUserDegreeModel.MapID;
                ViewBag.deg_text = businessUserDegreeModel.Degree_Map;

Incedo_Octavius_Demo_2/Views/BusinessUserDegreeModels/Create.cshtml
@model Incedo_Octavius_Demo_2.Models.BusinessUserDegreeModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@ViewBag.msg

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BusinessUserDegreeModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Degree_Map, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Degree_Map, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Degree_Map, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
                
            @Html.LabelFor(model => model.Degree_Master, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Degree_Master, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.Parent_Degree_ID, ViewBag.DegreeListItem as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Degree_Master, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Incedo_Octavius_Demo_2/Views/BusinessUserDegreeModels/Delete.cshtml
@model Incedo_Octavius_Demo_2.Models.BusinessUserDegreeModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BusinessUserDegreeModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Degree_Map)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Degree_Map)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Degree_Master)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Degree_Master)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Incedo_Octavius_Demo_2/Views/BusinessUserDegreeModels/Details.cshtml
@model Incedo_Octavius_Demo_2.Models.BusinessUserDegreeModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BusinessUserDegreeModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Degree_Map)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Degree_Map)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Degree_Master)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Degree_Master)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MapID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Incedo_Octavius_Demo_2/Views/BusinessUserDegreeModels/Edit.cshtml
@model Incedo_Octavius_Demo_2.Models.BusinessUserDegreeModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BusinessUserDegreeModel</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MapID)

        <div class="form-group">
            @Html.LabelFor(model => model.Degree_Map, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Degree_Map, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Degree_Map, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Degree_Master, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Degree_Master, new { htmlAttributes = new { @class = "form-control" } })*@


                @Html.DropDownListFor(model => model.Parent_Degree_ID, ViewBag.DegreeListItem as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Degree_Master, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Incedo_Octavius_Demo_2/Views/BusinessUserDegreeModels/Index.cshtml
@model IPagedList<Incedo_Octavius_Demo_2.Models.BusinessUserDegreeModel>

@{
    ViewBag.Title = "Index";
}
@using PagedList.Mvc;
@using PagedList;
<h2>Degree Business Rules</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().Degree_Map)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Degree_Master)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Degree_Map)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Degree_Master)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MapID }) |
            @*@Html.ActionLink("Details", "Details", new { id=item.MapID }) |*@
            @Html.ActionLink("Delete", "Delete", new { id=item.MapID })
        </td>
    </tr>
}

</table>
@Html.PagedListPager(Model,i=>Url.Action("Index","BusinessUserDegreeModels",new {i,search=Request.QueryString["search"]}))